### ISSUE TITLE
How can I get the "DeepFlow and DeepMatching binaries" ?

### ISSUE THREAD

**Issue by bemoregt** [ryanfb/torch-warp#4]
Hi, @ryanfb 

How can I get the "DeepFlow and DeepMatching binaries" ?

I've got the errors.

Thanks.

**Comment by ryanfb** [comment]
You'll need to go to the [DeepFlow](http://lear.inrialpes.fr/src/deepflow/) and [DeepMatching](http://lear.inrialpes.fr/src/deepmatching/) webpages, download the source appropriate to your platform, compile them, and place the resulting binaries in your `torch-warp` directory named as `deepflow2-static` and `deepmatching-static`.

**Comment by bemoregt** [comment]
OK, I see.

I will try your suggestion.

Many Thanks.

2017-06-15 22:42 GMT+09:00 Ryan Baumann <notifications@github.com>:
